version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: sulu_nginx
    ports:
      - 8080:80
    volumes:
      - ./sulu/:/var/www/project:cached
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
    depends_on:
      - php

  php:
    build:
      context: php/.
      args:
        USER_ID: 1000
    container_name: sulu_php
    volumes:
      - ~/.composer/cache:/home/sulu/.composer/cache/:cached
      - ./sulu:/var/www/project:cached
    environment:
      - DATABASE_URL=pdo-pgsql://test:test123@sulu_db/sulu?charset=UTF-8

  db:
    image: postgres:12-alpine
    container_name: sulu_db
    env_file:
      - db/settings.env

